[package]
name = "oxidite-utils"
version = "0.1.0"
edition = "2021"
authors = ["Meshack Bahati Ouma <bahatikylemeshack@gmail.com>"]
description = "Utility functions and helpers for the Oxidite web framework"
license = "MIT"
repository = "https://github.com/Kyle6012/rust-oxidite"
keywords = ["utilities", "helpers", "web", "framework", "rust"]
categories = ["web-programming"]


[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
uuid = { version = "1.11", features = ["v4", "serde"] }
base64 = "0.22"
rand = "0.9"
regex = "1.11"
